# Generated by Django 3.0.2 on 2020-02-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_auto_20200131_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
