# Generated by Django 3.0.2 on 2020-02-02 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0007_auto_20200201_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='balanced_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='fun_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='personalinfomodel',
            name='profile_image',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
