# Generated by Django 3.0.5 on 2020-05-19 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_templatemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='Personal_summary',
            field=models.TextField(default=0, verbose_name='Personal Summary'),
            preserve_default=False,
        ),
    ]
