# Generated by Django 3.0.5 on 2020-05-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0012_personalinfomodel_personal_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalinfomodel',
            name='Personal_summary',
        ),
        migrations.AddField(
            model_name='personalinfomodel',
            name='Profile',
            field=models.TextField(default=0, verbose_name='Profile'),
            preserve_default=False,
        ),
    ]
