# Generated by Django 3.0.5 on 2020-05-26 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0014_auto_20200522_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='Temp',
            field=models.CharField(choices=[('lumia', 'Lumia'), ('office', 'Office'), ('personal', 'Personal')], default='', max_length=30, verbose_name='Pick Your Template'),
        ),
    ]
