# Generated by Django 3.0.2 on 2020-01-23 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinfomodel',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
