# Generated by Django 3.0.2 on 2020-01-31 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_personalinfomodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='profile_image'),
        ),
    ]
