# Generated by Django 3.0.2 on 2020-01-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200131_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalinfomodel',
            name='image',
            field=models.ImageField(default='', upload_to='profile_image'),
        ),
    ]
