# Generated by Django 3.0.5 on 2020-05-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_auto_20200515_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='Infromation',
            field=models.TextField(default='', verbose_name='Details'),
        ),
    ]
