# Generated by Django 3.0.5 on 2020-05-22 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20200519_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatemodel',
            name='Temp',
            field=models.CharField(choices=[('lumia', 'Lumia'), ('office', 'Office')], default='', max_length=30, verbose_name='Pick Your Template'),
        ),
    ]
